### ISSUE TITLE
Why not use the MELPA package?

### ISSUE THREAD

**Issue by felipernb** [dracula/spacemacs#2]
I've installed the regular Emacs MELPA package on Spacemacs by adding `dracula-theme` to  `dotspacemacs-additional-packages`. i.e.:

```
dotspacemacs-additional-packages '(
    editorconfig
    dracula-theme
)
```

Why is that not the recommended way? That would also have the benefit of getting automatic updates whenever the MELPA package changes.

**Comment by GuilhermeCaruso** [comment]
In fact, this shape is also correct, since melpa has integration with spacemacs. The method described in the repository guarantees only full compatibility regardless of the version / branch.
